- .github/dependabot.yml 
A few notes:
- `label`'s default value is `dependencies`, so I left that off
- `rebase-strategy`'s default value is `auto`, so I left that off
- `live` is not a supported YML setting, unfortunately, so to get "live" PRs opened when we update our own packages, we'll need to bump each dependabot file individually.
Also note that this config should be pretty portable -- one issue we'll need to rectify is the main branch name on different repositories differs.
> Implement standard dependabot

- .eslintrc.js
- jest.config.js
- package.json
- tsconfig.json
- yarn.lock
- `@metamask/eslint-config*@6.0.0`
- Update `.eslintrc.js`
- Remove `eslint-plugin-json`
- Use `--cache` option for `eslint`
- Use `prettier` directly to lint JSON files
- Extend `@metamask/eslint-config-jest` for test files
> @metamask/eslint-config@6.0.0, update lint config and scripts

- tsconfig.json
Updates the `lib` field of `tsconfig.json` to use `ES2020` while still targeting `ES2017`.
We compile our TypeScript source using `tsc` to the `dist` folder, which produces `ES2017`-compatible code, even if we use `ES2020` features in our source code.
> Use ES2020 lib in TypeScript

- .github/dependabot.yml
This will make dependabot less noisy.
> Use only production updates in dependabot

- package.json
Updates the `prepublishOnly` script to build, lint, and then test.
The reason we build first is because if we ever have e.g. JavaScript tests that are supposed to test things in `dist`, linting will fail if the build isn't up-to-date.
> Update prepublishOnly script

- .github/dependabot.yml
As suggested by @rekmarks , let's only use dependabot for MetaMask updates.
> Only use dependabot for metamask updates

- tsconfig.json
This way, since `esModuleInterop` is `true`, our compiled `.js` files can be imported using both `require` and `import` without issue.
> Compile TypeScript modules to CommonJS instead of ES6

- .github/workflows/build-test.yml
- .yarnrc
- package.json
- yarn.lock
The template now uses `@lavamoat/allow-scripts` to control which scripts run during install. The `setup` script has been added as well, which is our conventional name for the script that runs `install` followed by `allow-scripts`. Also a `.yarnrc` file has been added to ensure that `--ignore-scripts` is always set.
Closes #51
> Add `@lavamoat/allow-scripts`

- .github/workflows/build-test.yml
The "all-jobs-pass" job no longer checks out the repository. [It had only included a checkout as a placeholder step](https://github.com/MetaMask/metamask-module-template/pull/19#discussion_r493757800), but this isn't necessary anymore now that we have the "Great success!" message. That can serve as our placeholder instead.
> Remove unnecessary checkout

- package.json
`tsc` will overwrite any existing files, but it will not delete anything that's not a subset of its output. Therefore, we should manually clean the `dist` directory on builds. I'd bet money that we have published nonsense files because of this.
> Clean the output directory on builds

- jest.config.js
Ensures that coverage is collected from all source files as opposed to just those that are tested. This behavior is controlled by the `collectCoverageFrom` field in `jest.config.js`.
> Collect coverage from all source files

- .eslintrc.js
- .prettierrc.js
- .prettierrc.yml
- package.json
`@metamask/eslint-config` handles the Prettier configuration for `eslint-plugin-prettier`, but not for the use of `prettier` in e.g. the `lint:misc` package script.
This also updates the `lint:misc` script to exclude `CHANGELOG.md` from Prettier linting. This is because we're going to start auto-generating (and validating) changelogs using https://github.com/MetaMask/auto-changelog.
> Add .prettierrc.yml, don't run Prettier on CHANGELOG.md

- .github/workflows/build-test.yml
The latest version of `actions/setup-node@v2` appears to act the same, except that it has better caching.
> Use `actions/setup-node@v2` instead of `actions/setup-node@v1`

- README.md
This section includes the test and release information that was present already, but adds a "Setup" section to explain how to setup the development environment. It also explains the `yarn setup` command, which is a common point of confusion for new contributors.
Linting instructions have been added alongside the test instructions as well.
> Add 'Contributing' section to README

- .github/workflows/build-test.yml
npm dependencies are now cached between CI runs. If a cache is found that used the same OS, Yarn version, and `yarn.lock` file, it is restored.
The `actions/cache@2` action (provided by GitHub) is used for caching. The way this action works is that it will restore the cache at the specified path if a matching cache is found. If no matching cache is found, it will run the job as normal and cache whatever it finds in that directory at the end of the job.
The Yarn cache directory is cached instead of `node_modules` because it contains the exact tarball that yarn downloaded from the registry, unaffected by postinstall scripts. This is particularly important when using the `actions/cache@v2` action, because it can only create a cache at the end of a job. So we need to ensure the cached path is …
> Add npm dependency caching

- .github/workflows/build-test.yml
When checking to see whether the current PR was for a release candidateor not, we were checking the wrong variable. `github.ref` contains the branch name if the action was triggered by a branch event, but in this case it's triggered by a `pull_request` event. For `pull_request` events, `github.ref` is set to `refs/pulls/[PR number]/merge`, so nothing was being recognized as a release candidate.
Instead it now checks `github.head_ref`, which is set to the branch name if it was triggered by `pull_request`. This workflow technically has two triggers: pushes to the `main` branch, and `pull_request`. But a push to the main branch is never a release candidate, so it's sufficient to just check `github.head_ref`.
> Fix CI changelog validation

- jest.config.js
This PR fixes a typo in the `collectCoverageFrom` array in `jest.config.js` that excluded directories within `./src` from coverage collection.
> Fix test coverage config

- .github/workflows/build-test.yml
Adds a `! git diff --exit-code` check to CI after the build step to ensure that the working tree remains clean after building. We don't expect to _need_ this check for every repository, but it should always pass for every repository, and is very fast as well!
> Add git working tree check to CI

- package.json
Add the `--no-error-on-unmatched-pattern` flag to the `prettier` invocation to prevent it from erroring if a particular file pattern is not matched. The patterns we have may be unmatched in certain repositories, for example in monorepos without `.yml` files in a particular package.
The reason we want to ignore these errors rather than remove the unmatched patterns is because it's very easy to forget to add them back should matching files be added, and then those files will not be linted for a potentially long period of time.
> Prevent prettier error on unmatched patterns

- package.json
- tsconfig.build.json
- tsconfig.json
Currently, test files are excluded from TypeScript's purview via the
`exclude` option in `tsconfig.json`. This is helpful when compiling
because it means that test files will not be included in the build
directory. However, for development, this is unnecessary, as we want
TypeScript to "see" and resolve types across all files in the project.
This commit splits off the build-specific settings from `tsconfig.json`
into a `tsconfig.build.json` file, which will exclusively be used in the
`yarn build` script.
> Extract build-only TypeScript config

- tsconfig.json
The filesystem used by macOS features case-insensitive lookup behavior:
if a file `foo.ts` exists, it can be referred to using `Foo.ts`. The
filesystems that Windows and Linux (at least historically) use, however,
exhibit case-sensitive lookup behavior. Usually TypeScript uses the same
rules as the filesystem on which it's running, so if `Foo.ts` is a valid
way to refer to a file `foo.ts`, then technically, it can be imported
the same way. With `forceConsistentCasingInFileNames` it will no longer
honor the native filesystem behavior and will enforce that a file is
imported using the exact name as it has been given.
See: <https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames>
---
Fixes #103.
> Enable forceConsistentCasingInFileNames: true

- .github/workflows/build-test.yml
- jest.config.js
- package.json
- yarn.lock
Adds `jest-it-up` to the template. [`jest-it-up`](https://github.com/rbardini/jest-it-up) is a neat package that detects when coverage has increased, and automatically your coverage minimums in the Jest config. The only requirements made of your Jest config are that (1) it is a conventional `jest.config.js` file and (2) its `coverageReporters` includes `json-summary`. Consequently, this PR converts the Jest config file from TypeScript back to plain JavaScript, and adds the required coverage reporter.
I believe that the benefits conferred by `jest-it-up` outweigh those of using TypeScript for the config file, which rarely changes and is never consumed by application code. Meanwhile,  `json-summary` outputs a single JSON file to the `coverage/` directory and does not appear to impact …
> Add jest-it-up

- tsconfig.json
I have found, when debugging TypeScript errors, that said errors can get
truncated if the types involved are even remotely non-trivial. I have
also found that type information which appears on hover can get
truncated sometimes as well. This can be frustrating, but fortunately,
the `noErrorTruncation` option in `tsconfig.json` can be used to turn
this off. I don't think that many people know about this option, and I'm
not sure why it's `false` by default, but here we flip it to `true`.
> Don't truncate info/error messages from TypeScript

- package.json
- yarn.lock
The Jest types have been updated to match the current Jest version. This resolves a peer dependency warning we were getting from `ts-jest`.
> Update `@types/jest` to match Jest version

- .github/workflows/publish-release.yml
- package.json
- scripts/prepack.sh
This adds the missing `SKIP_PREPACK` environment variable to the publish actions, to avoid running scripts.
> Add `SKIP_PREPACK` environment variable to publish actions

- .github/workflows/publish-release.yml
`runs-on` is not compatible with `uses`/`with`:
```
The workflow is not valid. .github/workflows/publish-release.yml
(Line: 108, Col: 5): Unexpected value 'uses' .github/workflows/publish-release.yml
(Line: 109, Col: 5): Unexpected value 'with'
```
https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
I added this on accident in #123.
> Remove invalid `runs-on` from publish workflow

- .github/workflows/publish-release.yml
`get-release-version` was missing a checkout, so running it would result in an error because the script cannot be found.
> Check out repository in `get-release-version` for publishing docs

- .github/workflows/build-test.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-release.yml
- .github/workflows/require-additional-reviewer.yml
This adds [`actionlint`](https://github.com/rhysd/actionlint) to automatically lint GitHub Actions workflows. This can catch potential errors such as the one caused in #123.
> Lint GitHub Actions workflows

- .github/workflows/build-test.yml
Inspired by MetaMask/controllers#941, this parallelises the build, lint, and test actions. This hypothetically speeds up CI.
> Parallelise build, lint, and test actions

- .github/workflows/create-release-pr.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-rc-docs.yml
- .github/workflows/publish-release.yml
- scripts/get.sh
`::set-output` is deprecated. This replaces it with the updated way to do it.
> Replace deprecated GitHub actions commands

- .github/workflows/publish-release.yml
Use major versions of MetaMask CI actions so we don't have to bump them manually for smaller changes.
> Use major versions of MetaMask CI actions

- .github/workflows/build-test.yml
- package.json
* Add back support for maintenance version 14 (see https://github.com/MetaMask/metamask-module-template/pull/131#issuecomment-1300362039)
* CI build for current nodejs version 19
(suggestion: we could change the policy to only support the latest maintenance release starting with the EOL of v14 in 2023-04, which would make the number of built versions more reasonable again)
> Support node 14

- .github/workflows/build-test.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-rc-docs.yml
Turns out `ubuntu-latest` is [still](https://github.com/actions/runner-images#available-images) pointing at `ubuntu-20.04`, so this currently does not do anything. It's intended to normalize tagging with other workflows, and make sure runners stay up to date without need for manual updates. This is in line with GH general recommendations.
https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/
> ci: change image tag from ubuntu-20.04 to ubuntu-latest

- package.json
- yarn.lock
TypeScript has been updated to the latest stable version. The TypeScript ESLint plugin and parser have been updated to versions that support this TypeScript version as well.
> Update TypeScript to latest stable version

- .github/workflows/build-test.yml
`actionlint@1.6.22` has some nice improvements like removing and detecting use of the deprecated workflow commands.
> Bump `actionlint` to 1.6.22

- .github/workflows/build-test.yml
- .github/workflows/publish-release.yml
This makes the publish workflow only run after the build, lint, and test steps have completed successfully. It does a workflow call to `publish-release.yml`, if the current commit is a release commit.
> Run publish after build, lint, test completed successfully

- .github/workflows/publish-release.yml
The action `MetaMask/action-npm-publish` has been updated to v2, which uses Yarn for publishing rather than npm. This ensures the publish step works correctly with Yarn-specific dependency protocols such as `workspace:`.
The `.yarn-state.yml` file needs to be cached and restored during publish to ensure that Yarn can run the `prepack` script. The prepack step is a no-op here because we have `SKIP_PREPACK` set, but there is no way to tell Yarn to not attempt running it.
Since we're no longer using npm, we don't need to set `ignore-scripts` in the npm config anymore either.
> Update action-npm-publish to support Yarn protocols

- .github/dependabot.yml
We removed `dependabot.yml` in #121, because it was not supported by Yarn 3. It is now supported, meaning that we can add it again.
> Add `dependabot.yml` again

- .github/workflows/build-test.yml
- .github/workflows/publish-release.yml
Secrets in a workflow called through `workflow_call` require secrets to be defined explicitly: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
> Add `NPM_TOKEN` to publish-release workflow call

- .github/workflows/build-lint-test.yml
- .github/workflows/main.yml
The workflows have been reorganized to use one "main" workflow for any push to the main branch, with additional jobs being triggered from there using `workflow_call`. This mirrors the change made recently in the controllers repository as part of the monorepo branch.
This makes more sense semantically every since we moved the publish step to be triggered by a push to `main`. Since then, it seend wrong to call that workflow "build-test" because it also did publishing. Now the "build-test" workflow is distinct, and it's the "main" workflow that triggers publishing.
> Reorganize GitHub Action workflows

- .github/workflows/main.yml
The `is-release` job condition now includes a check for the event trigger type, preventing it from running on `pull_request` events. This ensures we only release from the main branch, and it acts as further protection against running the `action-is-release` action in response to a `pull_request` event (it fails with a confusing error in that situation).
The comment has been improved as well.
Original description:
The `is-release` job condition is now compatible with more release workflows. Previously it assumed that release commits were made by GitHub Actions, but that's not true anymore in some of our repositories.
Instead, we now ensure just that the triggering event was a `push` event. `push` events are only triggered on this workflow for the main branch, so that will omit any events …
> Improve compatibility of `is-release` job condition

- .eslintrc.js
The `.yarn` folder contains auto-generated files, and should not be linted by ESLint.
I've added the folder to the `ignorePatterns` to prevent this.
> Ignore `.yarn` folder in ESLint

- jest.config.js
`babel` is the default value for `coverageProvider` and since we've seen some weird behaviour with `v8` I propose we use the default instead.
> Prefer Babel for Jest coverage

- .eslintrc.js
The ESLint configuration for test modules now includes Node.js lint rules. Our jest tests are always run with Node.js.
This was done recently in https://github.com/MetaMask/eth-json-rpc-provider/pull/6 to allow the use of Node.js globals in tests.
> Update ESLint test config to include Node.js rules

- README.md
The API section of the README now includes a link to the API documentation. The template instructions have called this out as well, so that people remember to update the URL.
https://github.com/MetaMask/eth-json-rpc-provider/blob/main/README.md
> Add API documentation links to README

- .github/workflows/publish-docs.yml
I've updated `peaceiris/actions-gh-pages` to a more recent version which does not use Node.js 12 anymore for running the action. Node.js 12 has been end-of-life for some time now.
> Update GitHub Actions docs action to remove dependency on Node.js 12

- tsconfig.json
After https://github.com/MetaMask/metamask-extension/commit/524ab66a16ace5d2088800c9c1203f42e5e1acbd has been merged, I believe we can start letting our modules target `ES2020`.
https://caniuse.com/?feats=mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nullish_coalescing,mdn-javascript_builtins_globalthis,es6-module-dynamic-import,bigint,mdn-javascript_builtins_promise_allsettled,mdn-javascript_builtins_string_matchall,mdn-javascript_statements_export_namespace,mdn-javascript_operators_import_meta
Open to thoughts and feedback from the team!
> Target `ES2020`

- .github/workflows/main.yml
actionlinting doesn't lint `vars` objects properly.
[Upgrading to .23 fixes the problem](https://github.com/jluque0101/iframe-execution-environment/pull/1#issuecomment-1483037014)
> Update actionlinting to fix a linting error

- .github/workflows/main.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-main-docs.yml
- .github/workflows/publish-rc-docs.yml
- .github/workflows/publish-release.yml
The `publish-docs` workflow has been updated to use a personal access token for publishing docs instead of using the `GITHUB_TOKEN`. This allows for more control over doc publishing permissions.
Fixes #184
This has been implemented in the `utils` library: https://github.com/MetaMask/utils/pull/96
> Use PAT for publishing docs

- .github/workflows/build-lint-test.yml
- README.md
- package.json
The minimum Node.js version has been updated to v16. CI is now testing v20 as well rather than v19, because v19 is now in maintenance mode and v20 is the current release.
We use v16 in a few places (extension and mobile, and a few libraries). This is the first place v20 has been used to my knowledge, but I doubt setting up an example ahead of time would teach is much in this case.
> Bump the minimum Node.js version to v16 and test v20

- .github/workflows/create-release-pr.yml
`release-type` can only be `major`, `minor`, or `patch`. The description has been updated to accurately reflect this.
1. Update the description of `release-type` field in the `create-release-pr` workflow.
> Update release-type description

- .github/workflows/publish-release.yml
Bumps `MetaMask/action-publish-release` to the latest version. This version includes support for pre-releases.
> Bump release action

- .github/workflows/create-release-pr.yml
Bumps `MetaMask/action-create-release-pr` to the latest version. This version includes support for pre-releases.
> Bump create release PR action

- tsconfig.build.json
It is a frustrating experience to want to see the source code of a module that's being imported in one's editor only to be presented with the `.d.ts` file when the module is Cmd-clicked (or "Go to Definition" is invoked). To fix this, TypeScript needs to be configured to generate source maps alongside `.d.ts` files.
I can enable this in the `core` repo first to see how this would work in practice.
> Generate source maps for `.d.ts` files

- .github/CODEOWNERS
- README.md
The CODEOWNERS file has been updated to use the new engineering team instead of the old devs team.
The README has been updated with instructions on updating the CODEOWNERS file as well, since we no longer want to use a single team as the code owners in most cases.
We intentionally aren't using the engineering team anywhere as a codeowner, but it's the best default we have.
> Replace devs team with engineering

- scripts/get.sh
- scripts/prepack.sh
The `-x` flag is typically used for debugging. When used in production, it can clutter the console output and make it difficult to tell what's happening.
The flag has been removed from the two small Bash scripts in this template.
This was done recently in this PR: https://github.com/MetaMask/eth-trezor-keyring/pull/182
> Remove the `-x` flag from Bash scripts

- .github/dependabot.yml
The old link simply redirected to `support.github.com`. I've updated it to the new GitHub Docs link.
> Fix broken Dependabot link

- .github/workflows/build-lint-test.yml
This changes the build and lint steps in CI to only run on the `.nvmrc` version. The Node version for these steps shouldn't matter. The test step is still run on all supported Node versions.
We made this change in a few other repositories already, but it was never applied to the module template.
> Run build and lint steps in CI on `.nvmrc` Node version

- package.json
- yarn.lock
Versions >=2.27.0 of `eslint-plugin-import` have a regression, causing the import order to change. The recommended version in the ESLint config is `~2.26.0` for now.
> Downgrade eslint-plugin-import to ~2.26.0

- tsconfig.json
TypeScript excludes `node_modules` by default (among other directories) if you don't specify `exclude` in the TS config, but if you specify `exclude`, then you need to make to explicitly list `node_modules`.
I believe we have started adding this slowly as we've remembered, but here is the latest example: https://github.com/MetaMask/create-release-branch/pull/93
> Exclude node_modules from TS compilation

- package.json
- scripts/prepack.sh
The `yarn pack` command is run by the `npm-publish` action prior to publishing the package. Unfortunately, this command does not work as the `prepack` lifecycle script is overridden to run `yarn build:clean`, which was removed when this repo was converted to use `tsup` for building. `tsup` already clears the `dist` directly, so in practice a `build:clean` script is not usually necessary, but there are occasions where we want to _really_ be sure that `dist` does not exist, and publishing is one of them. Hence, this commit adds back `build:clean`, which should fix `yarn pack` and the publishing workflow.
Running `yarn pack` should not produce any errors.
N/A, as this is a bugfix to this repo.
> Fix 'yarn pack'

- .github/workflows/build-lint-test.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/main.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-release.yml
This bumps `actions/checkout` and `actions/setup-node` to v4 (using Node.js 20), to replace the deprecated v3 actions (using Node.js 16).
> Replace deprecated GitHub actions

- .github/workflows/build-lint-test.yml
`corepack` is not currently supported in `@actions/setup-node` and this means installation of dependencies fail when using yarn >v1:
- https://github.com/actions/setup-node/pull/901
This hacks around it by running `@actions/setup-node` twice: once before checkout to install the node-version, so that `corepack enable` can be run, after which the normal flow starting with checkout can proceed.
Since `.nvmrc` is not available before checkout, it also implies not using `.nvmrc` to specify node-version for this workflow anymore.
An alternative to this would be forking `@actions/setup-node` with the patch from the PR linked above but sounds not worth it.
> ci: run `corepack enable` before installing dependencies

- .github/workflows/build-lint-test.yml
- package.json
- yarn.config.cjs
[As of October 29](https://github.com/nodejs/Release/tree/87462aac66fe3ce1ee1e3f812af83ccef9873782), Node.js 22 is the active `lts` version, and we should start to configure our repositories to use it as the latest supported version. This also updates our minimum supported Node versions for 18 and 20.
> chore: Use Node 22

- package.json
- yarn.lock
This bumps TypeScript to `~5.4.5`, which matches the version in the extension repository. This also fixes a potential issue with ESM when using `ts-bridge`.
> Bump TypeScript to `~5.4.5`

- .github/workflows/publish-release.yml
See changelog for `action-npm-publish`: https://github.com/MetaMask/action-npm-publish/blob/main/CHANGELOG.md#520
- We are using `MetaMask/action-npm-publish` v5 in `swaps-controller`: https://github.com/MetaMask/swaps-controller/blob/main/.github/workflows/publish-release.yml
> Update action-npm-publish to v5

- .github/workflows/build-lint-test.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/main.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-release.yml
This implements `MetaMask/action-checkout-and-setup`, which replaces the checkout and Node.js setup steps in CI.
> Implement `MetaMask/action-checkout-and-setup`

- .github/workflows/main.yml
- .github/workflows/security-code-scanner.yml
`MetaMask/Security-Code-Scanner` was renamed to `MetaMask/action-security-code-scanner`, and is now properly versioned as well. I've updated the workflow to use `MetaMask/action-security-code-scanner@v1`, and also changed it to run as part of the main workflow.
We use this in the Snaps repo: https://github.com/MetaMask/snaps/blob/0d9472d5f4110fdd9b657220a51c53cbac6a2675/.github/workflows/main.yml#L24-L34
> Update `MetaMask/action-security-code-scanner` and run as part of main workflow

- .github/workflows/publish-release.yml
When migrating to `MetaMask/action-checkout-and-setup`, we accidentally forgot to remove this `yarn install`. It's redundant, since the workflow itself will handle it.
> Remove unnecessary Yarn install from publish workflow
